### ISSUE TITLE
Add open module import exceptions

### ISSUE THREAD

**Issue by eborden** [jrp2014/smuggler2#1]
It is common style to utilize `NoImplicitPrelude` and import a prelude manually.

```hs
import Prelude

import ... -- Everything else
```

```hs
import RIO

import ... -- Everything else
```

```hs
import Relude

import ... -- Everything else
```

I'd love to be able to configure `smuggler2` to ignore these modules and leave them open by default.

Example: 
```hs
import Relude

import Data.Text (pack)
import Data.Text.Encoding (decodeASCII)
```

**Comment by eborden** [comment]
Note, I'd hope for this to be a list and not a single module declaration.

This:

`OpenImports=Relude,RIO,Prelude,Some.Module.Elsewhere`

Not this:

`Prelude=Relude`

**Comment by jrp2014** [comment]
Thanks.  I'll have a think about this.  At present `smuggler2` uses (a corrected version of) ghc's minimal import generation machinery to do the heavy lifting.  I just filter out the implicit modules generate the output.

This causes problems with some  cases (eg, `NoImplictPrelude` + `import Prelude (hiding x)` or the examples that you mention. 

So I suppose that the test should be
* get the minimal imports
* go through them and, if the original was open and it's listed on the openimports option, turn the minimal version.

I'll have to work through this to consider what should be done when imports are qualified, make sure that the pretty printing works, etc.

**Comment by jrp2014** [comment]
I've created a new branch called `openimports` which accepts something like `"-fplugin-opt=Smuggler2.Plugin:LeaveOpenImports:Prelude"`.  Perhaps you could kick the tyres.

It's pretty crude.  It just makes the modules that you specify open.  So it's probably better named `MakeOpenImports` as it doesn't check whether they were open in the first place...

**Comment by gittywithexcitement** [comment]
Hi, LeaveOpenImports works fine for me. Great feature! I'd say you can close this bug.
I confirmed that if Prelude (or whatever) has explicit imports in some file, smuggler2 does not change that file to open imports.
